Models/ErrorViewModel.cs
namespace Pedidos.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/ConsultaInformacionController.cs
using Dominio.IServicios;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Pedidos.Controllers {
    public class ConsultaInformacionController : Controller {
        private readonly IConsultaPedidoService _IConsultaPedidoService;

        public ConsultaInformacionController(IConsultaPedidoService iConsultaPedidoService) {
            _IConsultaPedidoService = iConsultaPedidoService;
        }

        [HttpPost]
        public async Task<ActionResult> ConsultaPedidosGeneral() {
            var lista = await _IConsultaPedidoService.ConsultaPedidosGeneral();

            return PartialView(lista);
        }
    }
}

Controllers/GeneradorPDFController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;

namespace Pedidos.Controllers {
    public class GeneradorPDFController : Controller {
        /* Hace referencia a IConfiguration para leer a appsettings */
        private readonly IConfiguration _config;

        public GeneradorPDFController(IConfiguration config) {
            _config = config;
        }

        [HttpPost]
        public JsonResult GenerarPDF(string html) { 
            var success = false;

            try {
                if (!string.IsNullOrEmpty(html)) {
                    /* Valor Facticio Posteriormente se tomará de BD */
                    var idUsuario = 2;
                    string sesion = "" + idUsuario;

                    html = "<meta charset='UTF-8'/><link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' integrity='sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T' crossorigin='anonymous'>" + html;
                    GenerarPDFService.GenerarPDF(html, _config, sesion);

                    success = true;
                }
            } catch(Exception e) { }

            return Json(new { success });
        }

        public ActionResult DownloadPDF(string namePDF) {
            /* Valor Facticio Posteriormente se tomará de BD */
            var idUsuario = 2;
            var session = "" + idUsuario;
            var ms = GenerarPDFService.LecturaPDF(_config, session);

            if (ms == null) { 
                return new EmptyResult();
            }

            return File(ms, "application/octet-stream", namePDF);
        }

        [HttpPost]
        public JsonResult GeneradorVisorPDF(string html) {
            var success = false;
            var encodedString = "";

            try {
                if (!string.IsNullOrEmpty(html)) {
                    /* Valor Facticio Posteriormente se tomará de BD */
                    var idUsuario = 2;
                    string sesion = "" + idUsuario;

                    html = "<meta charset='UTF-8'/><link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' integrity='sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T' crossorigin='anonymous'>" + html;
                    GenerarPDFService.GenerarPDF(html, _config, sesion);
                    
                    success = true;
                    var ms = GenerarPDFService.LecturaPDF(_config, sesion);
                    encodedString = Convert.ToBase64String(ms);
                }
            }
            catch (Exception) { }

            return Json(new { success, content = encodedString });
        }
    }
}

Controllers/GraficasController.cs
using Dominio.IServicios;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Pedidos.Controllers {
    public class GraficasController : Controller {

        public IActionResult Lineas() {
            ViewBag.xValues = new List<int> { 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150 };
            ViewBag.yValues = new List<int> { 7, 8, 8, 9, 9, 9, 10, 11, 14, 14, 15 };

            return View();
        }

        public IActionResult Barras() {
            return View();
        }

        public async Task<IActionResult> Pastel() {
            return View();
        }

        [HttpPost]
        public JsonResult Datos() {
            var xValues = new List<string> { "Italy", "France", "Spain", "USA", "Argentina" };
            var yValues = new List<int> { 55, 49, 44, 24, 15 };
            var barColors = new List<string> {
              "#b91d47",
              "#00aba9",
              "brown",
              "#e8c3b9",
              "#1e7145"
            };
            var lista = new {
                xValues,
                yValues,
                barColors
            };

            return Json(lista);
        }

        /* Ejemplo para descargar PDF */
        public FileResult DescargarPDF() {
            var fileBytes = System.IO.File.ReadAllBytes(@"C:\Prueba.pdf");
            string filename = "Grafica.pdf";

            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, filename);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Pedidos.Models;
using System.Diagnostics;

namespace Pedidos.Controllers {
    public class HomeController : Controller {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger) {
            _logger = logger;
        }

        public IActionResult Index() {
            TempData["Llave1"] = "La llave 1";
            ViewData["Llave2"] = "La llave 2";

            ViewBag.Llave3 = "La llave 3";

            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/MapasController.cs
using Dominio.IServicios;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Pedidos.Controllers {
    public class MapasController : Controller {
        private readonly IConsultaGraficaService _IConsultaGraficaService;

        public MapasController(IConsultaGraficaService iConsultaGraficaService) {
            _IConsultaGraficaService = iConsultaGraficaService;
        }
        public ActionResult EstadosRepublicas() {
            return View();
        }

        public async Task<ActionResult> ERPastelAsync() {
            var lista = await _IConsultaGraficaService.ConsultaPedidosAgrupados();
            ViewBag.Modelo = lista;

            return View();
        }

        public async Task<ActionResult> TotalesEstadoRep(){
            var lista = await _IConsultaGraficaService.ConsultaPedidosEstadosRepublica();
            ViewBag.Modelo = lista;

            return View();
        }

        public ActionResult TotalesEstadosRegion() {
            return View();
        }

        public ActionResult TotalesEstadosGrupos() {
            return View();
        }

        public ActionResult MapaMexico() {
            return View();
        }

        public async Task<IActionResult> ConsultaEstadosPedido() {
            var lista = await _IConsultaGraficaService.ConsultaEstadosPedido();

            /* Vista parcial */
            return PartialView(lista);
        }
    }
}

Controllers/ReporteController.cs
using Dominio.IServicios;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Transporte;

namespace Pedidos.Controllers {
    public class ReporteController : Controller {
        private readonly IConsultaGraficaService _IConsultaGraficaService;

        public ReporteController(IConsultaGraficaService iConsultaGraficaService) {
            _IConsultaGraficaService = iConsultaGraficaService;
        }

        [HttpPost]
        public async Task<JsonResult> estadosRepublica() {
            var lista = await _IConsultaGraficaService.ConsultaEstadosRepublica();

            return Json(lista);
        }

        [HttpPost]
        public async Task<JsonResult> ConsultaTotalesPorRegion(){
            var lista = await _IConsultaGraficaService.ConsultaTotalesPorRegion();

            return Json(lista);
        }

        [HttpPost]
        public async Task<JsonResult> ConsultaTotalesPorEstadoPedido(PedidoEdoDTO modelo) { 
            var lista = await _IConsultaGraficaService.ConsultaTotalesPorEstadoPedido(modelo);
            return Json(lista);
        }
    }
}

Views/Graficas/Barras.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div id="panel">
    <canvas id="myChart" width="250" height="100"></canvas>
</div>

<script>
    $(document).ready(function () {
        document.getElementById("panel").setAttribute("data-pdf", "GraficaBarras.pdf");
        document.getElementById("panel").setAttribute("data-title", "Gráfica de Barras");
    });

    const xValues   = ["Italy", "France", "Spain", "USA", "Argentina"];
    const yValues   = [55, 49, 44, 24, 15];
    const barColors = ["red", "green", "blue", "orange", "brown"];

    new Chart("myChart", {
      type: "bar",
      data: {
        labels  : xValues,
        datasets: [{
          backgroundColor: barColors,
          data           : yValues
        }]
      },
      options: {
        legend: {display: false},
        title: {
          display: true,
          text   : "World Wine Production 2018"
        }
      }
    });
</script>

Views/Graficas/Lineas.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div id="panel">
    <canvas id="myChart" width="250" height="100"></canvas>
</div>
<script>
    $(document).ready(function () {
        document.getElementById("panel").setAttribute("data-pdf", "GraficaLineas.pdf");
        document.getElementById("panel").setAttribute("data-title", "Gráfica de Lineas");
    });

    var xValues = JSON.parse('@Html.Raw(Json.Serialize(ViewBag.xValues))');
    var yValues = JSON.parse('@Html.Raw(Json.Serialize(ViewBag.yValues))');

    new Chart("myChart", {
      type: "line",
      data: {
        labels  : xValues,
        datasets: [{
          fill           : false,
          lineTension    : 0,
          backgroundColor: "rgba(0,0,255,1.0)",
          borderColor    : "rgba(0,0,255,0.1)",
          data           : yValues
        }]
      },
      options: {
        legend: {display: false},
        scales: {
          yAxes: [{ticks: {min: 6, max:16}}],
        }
      }
    });
</script>

Views/Graficas/Pastel.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div id="panel">
    <canvas id="myChart" style="width:500px; max-width:700px"></canvas>
</div>

<script>
    $(document).ready(function () {
        document.getElementById("panel").setAttribute("data-pdf", "GraficaPastel.pdf");
        document.getElementById("panel").setAttribute("data-title", "Gráfica de Pastel");

        envioGenericos("/Graficas/Datos", null, generadorGrafica)
    });

    // Resultado viene desde el servidor
    function generadorGrafica( resultado ) {
        new Chart("myChart", {
            type: "pie",
            data: {
                labels  : resultado.xValues,
                datasets: [{
                    backgroundColor: resultado.barColors,
                    data           : resultado.yValues
                }]
            },
            options: {
                title: {
                    display: true,
                    text   : "World Wide Wine Production 2018"
                }
            }
        });
    }

    
</script>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Mapas/ConsultaEstadosPedido.cshtml
@model IEnumerable<Transporte.PedidoEdoDTO>

<div class="text-align-content-center col-md-3 offset-3">
    <label class="col-form-control" style="padding-top:5px">
        Estados del Pedido: 
    </label>
</div>

<div class="text-center col-md-3">
    <select class="form-control" id="selectorEstadoPedido">
        <option value="0">Todos</option>
        @foreach (var item in Model) {
            <option value="@item.CatEstadoPedidoId">@item.EstadoPedido</option>
        }
    </select>
</div>

Views/Mapas/ERPastel.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<script type="text/javascript" src="~/js/Graficas/AgrupadosPedidos.js"></script>
<!-- Región de trabajo -->
<div id="panel" data-prefix="TotalesPastel.PDF">
    <h1 class="text-center">Totales por Estado Pedido</h1>
    <div class="row">
        <div class="col-md-7 col-xl-4">
            <div id="chart" style="width:100%;padding-bottom:20px;"></div>
        </div>
        <div class="col-md-5 col-xl-4">
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Estado del pedido</th>
                        <th scope="col">Cantidad</th>
                    </tr>
                </thead>
                <tbody id="CuerpoTabla">

                </tbody>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript">
    var data = JSON.parse('@Html.Raw(Json.Serialize(ViewBag.Modelo))');

	// Init de la página
	$(document).ready(function () {
		LlenadoData();
		RenderizadoGrafica();
	});
</script>

Views/Mapas/EstadosRepublicas.cshtml
@{
    ViewData["Title"] = "Estados de la Republica";
}

<script type="text/javascript" src="~/js/Utilerias/d3.layout.cloud.js"></script>
<script type="text/javascript" src="~/js/Graficas/EstadosRepublica.js"></script>

<!-- Región de trabajo -->
<div id="panel" data-prefix="EstadosRepbublica.PDF">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="text-center">Estados de la República</h1>
        </div>
    </div>
    <div id="panelLetras" class="text-center"></div>
</div>

<script type="text/javascript">
    words = null;

	var width = 900;
	var height = 400;

	// Init de la página
	$(document).ready(function () {
		estadosRepublica();
		RenderizadoPalabras();
	});
	
	function estadosRepublica() {
		envioGenericos("/Reporte/estadosRepublica", null, llenadoData);
	}

	function llenadoData(data) {
		words = data;
	}
</script>

Views/Mapas/MapaMexico.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<script src="~/js/Utilerias/mx.js"></script>
<script src="~/js/Utilerias/topojson.js"></script>
<script src="~/js/informacionGraficaMexico.js"></script>
<script src="~/js/Utilerias/dom-to-image.min.js"></script>
<script src="~/js/Graficas/MapaRepublica.js"></script>

<!-- Región de trabajo -->
<div id="panel" data-prefix="MapaMexico.PDF">
	<div class="row">
		<div class="col-lg-12">
			<h1 class="text-center" id="tituloGrafica">República Mexicana</h1>
		</div>
	</div>
	<div class="row" id="selectoresEstadoPedido"></div>
	<div id="chart" class="text-center"> </div>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		RenderizaMapa();
		selectoresEstadoPedido();

		$("#selectorEstadoPedido").change(function(){
			 RenderizaMapa();
		 })
	})
</script>

Views/Mapas/TotalesEstadoRep.cshtml
<script type="text/javascript" src="~/js/Graficas/AgrupadosEstadoRepublica.js"></script>

<!-- Región de trabajo -->
<div id="panel" data-prefix="TotalesEstadosRepublica.PDF">
	<div class="row">
		<div class="col-lg-12">
			<h1 class="text-center">Totales por estado de la República</h1>
		</div>
	</div>
	<div id="panelBarras" class="text-center"></div>
</div>

<script type="text/javascript">
	var data = JSON.parse('@Html.Raw(Json.Serialize(ViewBag.Modelo))');
	var datos = data.map( item => item.cantidad );
	var estadoRepublica = data.map( item => item.estadoRepublica )

	$(document).ready(function () {
		graficar();
	});	
</script>

Views/Mapas/TotalesEstadosGrupos.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<script type="text/javascript" src="~/js/Graficas/TotalesRegion.js"></script>

<div class="row">
	<!-- https://fontawesome.com/v5.15/icons?d=gallery&p=2&q=sta&c=shapes -->
	<div>
		<button class="btn btn-outline-success my-2 my-sm-0" type="button"
				onmouseover="tooltip.show('Gráfica de barra en grupos')" onmouseout="tooltip.hide();"
				onclick="tooltip.hide();transicionGrupo()">
			<i class="fa fa-bar-chart" aria-hidden="true"></i>
			Grupos
		</button>
		<button class="btn btn-outline-success my-2 my-sm-0" type="button"
				onmouseover="tooltip.show('Gráfica de barra en pila')" onmouseout="tooltip.hide();"
				onclick="tooltip.hide();transicionPila()">
			<i class="fa fa-bar-chart" aria-hidden="true"></i>
			Pilas
		</button>
	</div>
</div>
<!-- Región de trabajo -->
<div class="row" style="margin-left:15px">
	<div id="panel" data-prefix="TotalesRegionEstado.PDF">
		<div class="row">
			<div class="col-lg-12">
				<h1 class="text-center">Resultados por Grupos</h1>
			</div>
		</div>
		<div id="chart" style="width:100%" class="text-center"></div>
	</div>
</div>

<script type="text/javascript">

	var y0, my, mz, y1;

	var data = [];
	var margin = 20, numPisos = 0, segmentos = 5, numGrupos = 0;;
	var width = 1000, height = 370 - .5 - margin;

	// Init de la página
	$(document).ready(function () {
		RenderizadoGrafica();
	});

	function LlenadoData(datos) {
		data = datos.map(function (obj) {
			obj.piso = obj.estadoPedido;
			obj.grupo = obj.region;

			return obj;
		});
	};

</script>

Views/Mapas/TotalesEstadosRegion.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<script type="text/javascript" src="~/js/Graficas/TotalesEstadoRegion.js"></script>
<!-- Región de trabajo -->
<div id="panel" data-prefix="TotalesRegionEstado.PDF">
	<h1 class="text-center">Totales por Región y Estado</h1>
	<div id="chart-container"></div>
</div>

<script type="text/javascript">
	var data = [];
	var Regiones = [];
	var Estados = [];

	$(document).ready(function () {
		RenderizadoGrafica();
	});
	
	function LlenadoData() {
		data = data.map(function (obj) {
			return obj;
		});
		
		console.log(data);
	};

	function ObtenerDatos(datos) {
		data = datos;
};

	
</script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Pedidos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/tooltip.css" asp-append-version="true" />
    @*<link rel="stylesheet" href="~/Pedidos.styles.css" asp-append-version="true" />*@
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="~/js/Utilerias/FuncionesGenerales.js?1"></script>
    <script type="text/javascript" src="~/js/Utilerias/tooltip.js"></script>
    <script type="text/javascript" src="~/js/Utilerias/d3.colores.js"></script>
    <!--<script type="text/javascript" src="~/js/d3.layout.cloud.js"></script>-->
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.3/jspdf.min.js"></script>
    <script type="text/javascript" src="https://d3js.org/d3.v3.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.8.0/chart.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Pedidos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Mapas" asp-action="EstadosRepublicas">Estados República</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Mapas" asp-action="ERPastel">Mapas Estados República</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Mapas" asp-action="TotalesEstadoRep">Totales Estados República</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Mapas" asp-action="TotalesEstadosRegion">Totales República Region</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Mapas" asp-action="TotalesEstadosGrupos">Totales República Grupos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Mapas" asp-action="MapaMexico">Mapa México</a>
                        </li>
                    </ul>
                    <form class="form-inline my-2 my-lg-0">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="button"
                                onmouseover="tooltip.show('Descargar documento de la gráfica en formato PDF')"
                                onmouseout="tooltip.hide();"
                                onclick="tooltip.hide();GenerarPDF();">
                            <i class="fa fa-file-pdf"></i>
                            Descarga
                        </button>
                        <br />
                        <button class="btn btn-outline-success my-2 my-sm-0" type="button" 
                            onmouseover="tooltip.show('Generar vista previa de la gráfica')"
                            onmouseout="tooltip.hide();"
                            onclick="tooltip.hide();GenerarVisorPDF();" >
                            <i class="fa fa-save"></i>
                            Vista previa
                        </button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="contenedor">
        @RenderBody()
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <script type="text/javascript">
        SetupDescarga();
    </script>
</body>
</html>